### ISSUE TITLE
 “<<”  这个是什么意思

### ISSUE THREAD

**Issue by wongyue** [rujews/android-gradle-book-code#5]
task printList << {
    def numList =[1,2,3,4,5,6]
    println numList.getClass().name
}

方法名前面的这个尖括号，要删了才能运行，书里面没提到这个呀，但是看到每个task示例都带了这个尖括号，求解。。。。

**Comment by flysnoworg** [comment]
doLast方法的实现，快捷操作符。

doLast 等于 <<

**Comment by wongyue** [comment]
好滴，感谢，现在装的是5.1的，运行报错，后边查了一下换成4.6的就成功运行了
